name: check file encodings in PR
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
runs:
  using: "composite"
  steps:
    - name: list all changed files
      shell: bash
      run: |
        files=$(git diff --name-only origin/$GITHUB_BASE_REF...${{ github.sha }})
        IFS=$'\n'; files=($files); unset IFS;  # split the string into an array
        file --mime "${files[@]}"
    - name: list all changed files with the wrong encoding
      shell: bash
      run: |
        files=$(git diff --name-only origin/$GITHUB_BASE_REF...${{ github.sha }})
        IFS=$'\n'; files=($files); unset IFS;  # split the string into an array
        ! file --mime "${files[@]}" | grep -v "charset=utf-8\|charset=us-ascii\|charset=binary\| (No such file or directory)$"
